spring:
  datasource:
    master:
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/switch
    slave1:
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3307/switch
    slave2:
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3308/switch