server:
  port: 8888
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cache
mybatis:
  type-aliases-package: com.sciatta.dev.java.database.cache.model
  mapper-locations: classpath:mapper/*Mapper.xml